<h1> Final project CAPSON Kathia Campo  <h1>

<h1> Introduction | Business Undertanding <h1>

"According to the World Health Organization, the United States ranks 41st among the 52 highest-income nations in terms of traffic fatalities, surpassed only by Qatar, Saudi Arabia and Russia. It is also "now the most dangerous rich country in which a child can be born," concluded a new report published by Health Affairs magazine, based in part on the high risk of a young person dying after a car accident. . Among American teens between the ages of 15 and 19, car accidents rank as the leading cause of death.

It didn't use to be this way: Before the 1980s, the United States was at the forefront of driving safety, outperforming several wealthy countries. Today, the traffic accident fatality rate in the US, per 100,000 inhabitants, is almost double that of Canada and Australia, and is almost three and a half times that of the United Kingdom. Slovenia, Italy and Greece are also doing better" Bliss,L(2018,13 March) The highway crisis in the US: high mortality and poor safety Retrieved from https://www.univision.com/noticias/citylab-transporte/la-crisis-de-las-autopistas-en-eeuu-alta-mortalidad-y-escasa-seguridad

In order to reduce the frequency of car collisions in the US and making use of artificial intelligence, an algorithm will be developed to predict the severity of an accident given the weather, road and visibility conditions taken from a data frame.

 <h1>target audience<h1>

The target audience of the project are all drivers of the city of Seattle as well as the local government, and rescue agencies, it is hoped that with the model and its results warnings can be given before making decisions to reduce the number of accidents

<h1>Data Preprocessing<h1>

The data in the initial form is not ready for analysis. For this reason, first, we are going to remove the non-relevant columns. In addition to this, many of the features are from object data types that must be converted to numeric data types.

In analyzing the data set, it has been decided to work with only four characteristics: severity, weather conditions, road conditions and light conditions, "For now ".

In order to understand the data set well, different values have been verified in the characteristics.The results show, the target feature is imbalance, so we use a simple statistical technique to balance it

In [1]:
import csv

In [2]:
import numpy as np
import pandas as pd #primary data structure library
from __future__ import print_function #adds compatibility to python 2

In [3]:
# Read the csv file from other path (pc)
df = pd.read_csv('C:/Users/ASUS/Desktop/Python/Data-Collisions.csv',sep=','
                    )

print ('Data read into a pandas dataframe!')

Data read into a pandas dataframe!


C:\Users\ASUS\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [4]:
df

SEVERITYCODE           X          Y  OBJECTID  INCKEY  COLDETKEY  \
0                  2 -122.323148  47.703140         1    1307       1307   
1                  1 -122.347294  47.647172         2   52200      52200   
2                  1 -122.334540  47.607871         3   26700      26700   
3                  1 -122.334803  47.604803         4    1144       1144   
4                  2 -122.306426  47.545739         5   17700      17700   
5                  1 -122.387598  47.690575         6  320840     322340   
6                  1 -122.338485  47.618534         7   83300      83300   
7                  2 -122.320780  47.614076         9  330897     332397   
8                  1 -122.335930  47.611904        10   63400      63400   
9                  2 -122.384700  47.528475        12   58600      58600   
10                 1         NaN        NaN        14   48900      48900   
11                 1 -122.333831  47.547371        15   38800      38800   
12                 1 -122.356273  47.571375        16    2771       2771   
13                 1 -122.323966  47.606374        17   32800      32800   
14                 2 -122.317414  47.664028        19    1212       1212   
15                 1 -122.337663  47.617510        20  330878     332378   
16                 2 -122.344539  47.692012        21   46300      46300   
17                 1         NaN        NaN        23   23000      23000   
18                 2 -122.328270  47.571420        24  330833     332333   
19                 1 -122.383802  47.583715        25   97100      97100   
20                 2 -122.292403  47.732847        26    1347       1347   
21                 2 -122.313786  47.708535        28    1323       1323   
22                 1 -122.318169  47.615837        29   80000      80000   
23                 1 -122.337486  47.589746        31   28700      28700   
24                 2 -122.279658  47.553405        33    1268       1268   
25                 2 -122.312857  47.599218        34  320932     322432   
26                 1 -122.330730  47.615450        35  113300     113300   
27                 1 -122.385859  47.581191        36   64700      64700   
28                 1 -122.304990  47.611474        37    1083       1083   
29                 1         NaN        NaN        38   61500      61500   
...              ...         ...        ...       ...     ...        ...   
194643             1 -122.345863  47.612991    219510  307577     308857   
194644             1 -122.330298  47.603233    219511  312117     313537   
194645             2 -122.328079  47.604161    219512  307692     308972   
194646             1 -122.320756  47.608656    219513  312289     313709   
194647             2 -122.355449  47.704720    219514  308575     309855   
194648             1 -122.357624  47.635956    219515  307792     309072   
194649             2 -122.302382  47.626759    219516  307985     309265   
194650             2 -122.355298  47.684382    219517  310417     311717   
194651             1 -122.320780  47.614076    219519  309594     310874   
194652             1 -122.335527  47.617434    219520  308698     309978   
194653             2 -122.322097  47.649615    219521  308342     309622   
194654             1 -122.312679  47.719414    219522  311117     312437   
194655             2 -122.380016  47.664879    219523  310911     312231   
194656             2 -122.340474  47.614496    219524  312179     313599   
194657             1 -122.337137  47.610709    219525  307834     309114   
194658             1 -122.302554  47.584099    219528  311697     313057   
194659             1 -122.298955  47.717456    219529  308019     309299   
194660             2         NaN        NaN    219531  308990     310270   
194661             2 -122.306092  47.617881    219532  308532     309812   
194662             1 -122.337880  47.625793    219535  307802     309082   
194663             2 -122.299160  47.579673    219536  3

<h1> Data preprosessing <h1> 

The dataset in the original form is not ready for data analysis. In order to prepare the data, first, we need to drop the non-relevant columns. In addition, most of the features are of object data types that need to be converted into numerical data types.
After analyzing the data set, I have decided to focus on only four features, severity, weather conditions, road conditions, and light conditions, among others.
To get a good understanding of the dataset, I have checked different values in the features. The results show, the target feature is imbalance, so we use a simple statistical technique to balance it.

In [5]:
df["SEVERITYCODE"].value_counts()

1    136485
2     58188
Name: SEVERITYCODE, dtype: int64

As you can see, the number of rows in class 1 is almost three times bigger than the number of rows in class 2. It is possible to solve the issue by downsampling the class 1.

In [6]:
from sklearn.utils import resample

In [7]:
df_maj=df[df.SEVERITYCODE==1]
df_min=df[df.SEVERITYCODE==2]
df_maj_dsample=resample(df_maj, replace=False,
                            n_samples=58188,
                            random_state=123)
balanced_df=pd.concat([df_maj_dsample,df_min])
balanced_df.SEVERITYCODE.value_counts()

2    58188
1    58188
Name: SEVERITYCODE, dtype: int64

In [8]:
y=np.asarray(balanced_df["SEVERITYCODE"])
y[0:5]

array([1, 1, 1, 1, 1], dtype=int64)

<h1> Methodology <h1>

Once I have load data into Pandas Dataframe, used ‘dtypes’ attribute to check the feature names and their data types. Then I have selected the most important features to predict the severity of accidents in Seattle. Among all the features, the following features have the most influence in the accuracy of the predictions:
“WEATHER”,
“ROADCOND”,
“LIGHTCOND”
Also, as I mentioned earlier, “SEVERITYCODE” is the target variable.
I have run a value count on road (‘ROADCOND’) and weather condition (‘WEATHER’) to get ideas of the different road and weather conditions. I also have run a value count on light condition (’LIGHTCOND’), to see the breakdowns of accidents occurring during the different light conditions. The results can be seen below:

In [9]:
df["WEATHER"].value_counts()

Clear                       111135
Raining                      33145
Overcast                     27714
Unknown                      15091
Snowing                        907
Other                          832
Fog/Smog/Smoke                 569
Sleet/Hail/Freezing Rain       113
Blowing Sand/Dirt               56
Severe Crosswind                25
Partly Cloudy                    5
Name: WEATHER, dtype: int64

In [10]:
df["ROADCOND"].value_counts()

Dry               124510
Wet                47474
Unknown            15078
Ice                 1209
Snow/Slush          1004
Other                132
Standing Water       115
Sand/Mud/Dirt         75
Oil                   64
Name: ROADCOND, dtype: int64

In [11]:
df["LIGHTCOND"].value_counts()

Daylight                    116137
Dark - Street Lights On      48507
Unknown                      13473
Dusk                          5902
Dawn                          2502
Dark - No Street Lights       1537
Dark - Street Lights Off      1199
Other                          235
Dark - Unknown Lighting         11
Name: LIGHTCOND, dtype: int64

In [12]:
#import pandas as pd
#df1=pd.get_dummies(df["WEATHER"],prefix="WEATHER",drop_first=True)
#df1

In [13]:
#df=pd.concat([df,df1],axis=1)
#df

In [14]:
df["WEATHER"]=df["WEATHER"].astype('category')
df.dtypes

SEVERITYCODE         int64
X                  float64
Y                  float64
OBJECTID             int64
INCKEY               int64
COLDETKEY            int64
REPORTNO            object
STATUS              object
ADDRTYPE            object
INTKEY             float64
LOCATION            object
EXCEPTRSNCODE       object
EXCEPTRSNDESC       object
SEVERITYCODE.1       int64
SEVERITYDESC        object
COLLISIONTYPE       object
PERSONCOUNT          int64
PEDCOUNT             int64
PEDCYLCOUNT          int64
VEHCOUNT             int64
INCDATE             object
INCDTTM             object
JUNCTIONTYPE        object
SDOT_COLCODE         int64
SDOT_COLDESC        object
INATTENTIONIND      object
UNDERINFL           object
WEATHER           category
ROADCOND            object
LIGHTCOND           object
PEDROWNOTGRNT       object
SDOTCOLNUM         float64
SPEEDING            object
ST_COLCODE          object
ST_COLDESC          object
SEGLANEKEY           int64
CROSSWALKKEY         int64
H

In [15]:
df["WEATHER"]=df["WEATHER"].cat.codes
df

SEVERITYCODE           X          Y  OBJECTID  INCKEY  COLDETKEY  \
0                  2 -122.323148  47.703140         1    1307       1307   
1                  1 -122.347294  47.647172         2   52200      52200   
2                  1 -122.334540  47.607871         3   26700      26700   
3                  1 -122.334803  47.604803         4    1144       1144   
4                  2 -122.306426  47.545739         5   17700      17700   
5                  1 -122.387598  47.690575         6  320840     322340   
6                  1 -122.338485  47.618534         7   83300      83300   
7                  2 -122.320780  47.614076         9  330897     332397   
8                  1 -122.335930  47.611904        10   63400      63400   
9                  2 -122.384700  47.528475        12   58600      58600   
10                 1         NaN        NaN        14   48900      48900   
11                 1 -122.333831  47.547371        15   38800      38800   
12                 1 -122.356273  47.571375        16    2771       2771   
13                 1 -122.323966  47.606374        17   32800      32800   
14                 2 -122.317414  47.664028        19    1212       1212   
15                 1 -122.337663  47.617510        20  330878     332378   
16                 2 -122.344539  47.692012        21   46300      46300   
17                 1         NaN        NaN        23   23000      23000   
18                 2 -122.328270  47.571420        24  330833     332333   
19                 1 -122.383802  47.583715        25   97100      97100   
20                 2 -122.292403  47.732847        26    1347       1347   
21                 2 -122.313786  47.708535        28    1323       1323   
22                 1 -122.318169  47.615837        29   80000      80000   
23                 1 -122.337486  47.589746        31   28700      28700   
24                 2 -122.279658  47.553405        33    1268       1268   
25                 2 -122.312857  47.599218        34  320932     322432   
26                 1 -122.330730  47.615450        35  113300     113300   
27                 1 -122.385859  47.581191        36   64700      64700   
28                 1 -122.304990  47.611474        37    1083       1083   
29                 1         NaN        NaN        38   61500      61500   
...              ...         ...        ...       ...     ...        ...   
194643             1 -122.345863  47.612991    219510  307577     308857   
194644             1 -122.330298  47.603233    219511  312117     313537   
194645             2 -122.328079  47.604161    219512  307692     308972   
194646             1 -122.320756  47.608656    219513  312289     313709   
194647             2 -122.355449  47.704720    219514  308575     309855   
194648             1 -122.357624  47.635956    219515  307792     309072   
194649             2 -122.302382  47.626759    219516  307985     309265   
194650             2 -122.355298  47.684382    219517  310417     311717   
194651             1 -122.320780  47.614076    219519  309594     310874   
194652             1 -122.335527  47.617434    219520  308698     309978   
194653             2 -122.322097  47.649615    219521  308342     309622   
194654             1 -122.312679  47.719414    219522  311117     312437   
194655             2 -122.380016  47.664879    219523  310911     312231   
194656             2 -122.340474  47.614496    219524  312179     313599   
194657             1 -122.337137  47.610709    219525  307834     309114   
194658             1 -122.302554  47.584099    219528  311697     313057   
194659             1 -122.298955  47.717456    219529  308019     309299   
194660             2         NaN        NaN    219531  308990     310270   
194661             2 -122.306092  47.617881    219532  308532     309812   
194662             1 -122.337880  47.625793    219535  307802     309082   
194663             2 -122.299160  47.579673    219536  3

In [16]:
#import libraries
import pandas as pd
from sklearn.preprocessing import LabelEncoder
#creating an instance of labelencoder
labelencoder = LabelEncoder()


In [17]:
#assigning numerical values and storing it in another colum called "WEATHER_cat"
df["WEATHER_cat"]=labelencoder.fit_transform(df["WEATHER"])
#Display DataFrame
df


SEVERITYCODE           X          Y  OBJECTID  INCKEY  COLDETKEY  \
0                  2 -122.323148  47.703140         1    1307       1307   
1                  1 -122.347294  47.647172         2   52200      52200   
2                  1 -122.334540  47.607871         3   26700      26700   
3                  1 -122.334803  47.604803         4    1144       1144   
4                  2 -122.306426  47.545739         5   17700      17700   
5                  1 -122.387598  47.690575         6  320840     322340   
6                  1 -122.338485  47.618534         7   83300      83300   
7                  2 -122.320780  47.614076         9  330897     332397   
8                  1 -122.335930  47.611904        10   63400      63400   
9                  2 -122.384700  47.528475        12   58600      58600   
10                 1         NaN        NaN        14   48900      48900   
11                 1 -122.333831  47.547371        15   38800      38800   
12                 1 -122.356273  47.571375        16    2771       2771   
13                 1 -122.323966  47.606374        17   32800      32800   
14                 2 -122.317414  47.664028        19    1212       1212   
15                 1 -122.337663  47.617510        20  330878     332378   
16                 2 -122.344539  47.692012        21   46300      46300   
17                 1         NaN        NaN        23   23000      23000   
18                 2 -122.328270  47.571420        24  330833     332333   
19                 1 -122.383802  47.583715        25   97100      97100   
20                 2 -122.292403  47.732847        26    1347       1347   
21                 2 -122.313786  47.708535        28    1323       1323   
22                 1 -122.318169  47.615837        29   80000      80000   
23                 1 -122.337486  47.589746        31   28700      28700   
24                 2 -122.279658  47.553405        33    1268       1268   
25                 2 -122.312857  47.599218        34  320932     322432   
26                 1 -122.330730  47.615450        35  113300     113300   
27                 1 -122.385859  47.581191        36   64700      64700   
28                 1 -122.304990  47.611474        37    1083       1083   
29                 1         NaN        NaN        38   61500      61500   
...              ...         ...        ...       ...     ...        ...   
194643             1 -122.345863  47.612991    219510  307577     308857   
194644             1 -122.330298  47.603233    219511  312117     313537   
194645             2 -122.328079  47.604161    219512  307692     308972   
194646             1 -122.320756  47.608656    219513  312289     313709   
194647             2 -122.355449  47.704720    219514  308575     309855   
194648             1 -122.357624  47.635956    219515  307792     309072   
194649             2 -122.302382  47.626759    219516  307985     309265   
194650             2 -122.355298  47.684382    219517  310417     311717   
194651             1 -122.320780  47.614076    219519  309594     310874   
194652             1 -122.335527  47.617434    219520  308698     309978   
194653             2 -122.322097  47.649615    219521  308342     309622   
194654             1 -122.312679  47.719414    219522  311117     312437   
194655             2 -122.380016  47.664879    219523  310911     312231   
194656             2 -122.340474  47.614496    219524  312179     313599   
194657             1 -122.337137  47.610709    219525  307834     309114   
194658             1 -122.302554  47.584099    219528  311697     313057   
194659             1 -122.298955  47.717456    219529  308019     309299   
194660             2         NaN        NaN    219531  308990     310270   
194661             2 -122.306092  47.617881    219532  308532     309812   
194662             1 -122.337880  47.625793    219535  307802     309082   
194663             2 -122.299160  47.579673    219536  3

In [18]:
df["ROADCOND"]=df["ROADCOND"].astype('category')
df.dtypes

SEVERITYCODE         int64
X                  float64
Y                  float64
OBJECTID             int64
INCKEY               int64
COLDETKEY            int64
REPORTNO            object
STATUS              object
ADDRTYPE            object
INTKEY             float64
LOCATION            object
EXCEPTRSNCODE       object
EXCEPTRSNDESC       object
SEVERITYCODE.1       int64
SEVERITYDESC        object
COLLISIONTYPE       object
PERSONCOUNT          int64
PEDCOUNT             int64
PEDCYLCOUNT          int64
VEHCOUNT             int64
INCDATE             object
INCDTTM             object
JUNCTIONTYPE        object
SDOT_COLCODE         int64
SDOT_COLDESC        object
INATTENTIONIND      object
UNDERINFL           object
WEATHER               int8
ROADCOND          category
LIGHTCOND           object
PEDROWNOTGRNT       object
SDOTCOLNUM         float64
SPEEDING            object
ST_COLCODE          object
ST_COLDESC          object
SEGLANEKEY           int64
CROSSWALKKEY         int64
H

In [19]:
df["ROADCOND"]=df["ROADCOND"].cat.codes
df

SEVERITYCODE           X          Y  OBJECTID  INCKEY  COLDETKEY  \
0                  2 -122.323148  47.703140         1    1307       1307   
1                  1 -122.347294  47.647172         2   52200      52200   
2                  1 -122.334540  47.607871         3   26700      26700   
3                  1 -122.334803  47.604803         4    1144       1144   
4                  2 -122.306426  47.545739         5   17700      17700   
5                  1 -122.387598  47.690575         6  320840     322340   
6                  1 -122.338485  47.618534         7   83300      83300   
7                  2 -122.320780  47.614076         9  330897     332397   
8                  1 -122.335930  47.611904        10   63400      63400   
9                  2 -122.384700  47.528475        12   58600      58600   
10                 1         NaN        NaN        14   48900      48900   
11                 1 -122.333831  47.547371        15   38800      38800   
12                 1 -122.356273  47.571375        16    2771       2771   
13                 1 -122.323966  47.606374        17   32800      32800   
14                 2 -122.317414  47.664028        19    1212       1212   
15                 1 -122.337663  47.617510        20  330878     332378   
16                 2 -122.344539  47.692012        21   46300      46300   
17                 1         NaN        NaN        23   23000      23000   
18                 2 -122.328270  47.571420        24  330833     332333   
19                 1 -122.383802  47.583715        25   97100      97100   
20                 2 -122.292403  47.732847        26    1347       1347   
21                 2 -122.313786  47.708535        28    1323       1323   
22                 1 -122.318169  47.615837        29   80000      80000   
23                 1 -122.337486  47.589746        31   28700      28700   
24                 2 -122.279658  47.553405        33    1268       1268   
25                 2 -122.312857  47.599218        34  320932     322432   
26                 1 -122.330730  47.615450        35  113300     113300   
27                 1 -122.385859  47.581191        36   64700      64700   
28                 1 -122.304990  47.611474        37    1083       1083   
29                 1         NaN        NaN        38   61500      61500   
...              ...         ...        ...       ...     ...        ...   
194643             1 -122.345863  47.612991    219510  307577     308857   
194644             1 -122.330298  47.603233    219511  312117     313537   
194645             2 -122.328079  47.604161    219512  307692     308972   
194646             1 -122.320756  47.608656    219513  312289     313709   
194647             2 -122.355449  47.704720    219514  308575     309855   
194648             1 -122.357624  47.635956    219515  307792     309072   
194649             2 -122.302382  47.626759    219516  307985     309265   
194650             2 -122.355298  47.684382    219517  310417     311717   
194651             1 -122.320780  47.614076    219519  309594     310874   
194652             1 -122.335527  47.617434    219520  308698     309978   
194653             2 -122.322097  47.649615    219521  308342     309622   
194654             1 -122.312679  47.719414    219522  311117     312437   
194655             2 -122.380016  47.664879    219523  310911     312231   
194656             2 -122.340474  47.614496    219524  312179     313599   
194657             1 -122.337137  47.610709    219525  307834     309114   
194658             1 -122.302554  47.584099    219528  311697     313057   
194659             1 -122.298955  47.717456    219529  308019     309299   
194660             2         NaN        NaN    219531  308990     310270   
194661             2 -122.306092  47.617881    219532  308532     309812   
194662             1 -122.337880  47.625793    219535  307802     309082   
194663             2 -122.299160  47.579673    219536  3

In [20]:
#assigning numerical values and storing it in another colum called "WEATHER_cat"
df["ROADCOND_cat"]=labelencoder.fit_transform(df["ROADCOND"])
#Display DataFrame
df

SEVERITYCODE           X          Y  OBJECTID  INCKEY  COLDETKEY  \
0                  2 -122.323148  47.703140         1    1307       1307   
1                  1 -122.347294  47.647172         2   52200      52200   
2                  1 -122.334540  47.607871         3   26700      26700   
3                  1 -122.334803  47.604803         4    1144       1144   
4                  2 -122.306426  47.545739         5   17700      17700   
5                  1 -122.387598  47.690575         6  320840     322340   
6                  1 -122.338485  47.618534         7   83300      83300   
7                  2 -122.320780  47.614076         9  330897     332397   
8                  1 -122.335930  47.611904        10   63400      63400   
9                  2 -122.384700  47.528475        12   58600      58600   
10                 1         NaN        NaN        14   48900      48900   
11                 1 -122.333831  47.547371        15   38800      38800   
12                 1 -122.356273  47.571375        16    2771       2771   
13                 1 -122.323966  47.606374        17   32800      32800   
14                 2 -122.317414  47.664028        19    1212       1212   
15                 1 -122.337663  47.617510        20  330878     332378   
16                 2 -122.344539  47.692012        21   46300      46300   
17                 1         NaN        NaN        23   23000      23000   
18                 2 -122.328270  47.571420        24  330833     332333   
19                 1 -122.383802  47.583715        25   97100      97100   
20                 2 -122.292403  47.732847        26    1347       1347   
21                 2 -122.313786  47.708535        28    1323       1323   
22                 1 -122.318169  47.615837        29   80000      80000   
23                 1 -122.337486  47.589746        31   28700      28700   
24                 2 -122.279658  47.553405        33    1268       1268   
25                 2 -122.312857  47.599218        34  320932     322432   
26                 1 -122.330730  47.615450        35  113300     113300   
27                 1 -122.385859  47.581191        36   64700      64700   
28                 1 -122.304990  47.611474        37    1083       1083   
29                 1         NaN        NaN        38   61500      61500   
...              ...         ...        ...       ...     ...        ...   
194643             1 -122.345863  47.612991    219510  307577     308857   
194644             1 -122.330298  47.603233    219511  312117     313537   
194645             2 -122.328079  47.604161    219512  307692     308972   
194646             1 -122.320756  47.608656    219513  312289     313709   
194647             2 -122.355449  47.704720    219514  308575     309855   
194648             1 -122.357624  47.635956    219515  307792     309072   
194649             2 -122.302382  47.626759    219516  307985     309265   
194650             2 -122.355298  47.684382    219517  310417     311717   
194651             1 -122.320780  47.614076    219519  309594     310874   
194652             1 -122.335527  47.617434    219520  308698     309978   
194653             2 -122.322097  47.649615    219521  308342     309622   
194654             1 -122.312679  47.719414    219522  311117     312437   
194655             2 -122.380016  47.664879    219523  310911     312231   
194656             2 -122.340474  47.614496    219524  312179     313599   
194657             1 -122.337137  47.610709    219525  307834     309114   
194658             1 -122.302554  47.584099    219528  311697     313057   
194659             1 -122.298955  47.717456    219529  308019     309299   
194660             2         NaN        NaN    219531  308990     310270   
194661             2 -122.306092  47.617881    219532  308532     309812   
194662             1 -122.337880  47.625793    219535  307802     309082   
194663             2 -122.299160  47.579673    219536  3

In [21]:
df["LIGHTCOND"]=df["LIGHTCOND"].astype('category')
df.dtypes

SEVERITYCODE         int64
X                  float64
Y                  float64
OBJECTID             int64
INCKEY               int64
COLDETKEY            int64
REPORTNO            object
STATUS              object
ADDRTYPE            object
INTKEY             float64
LOCATION            object
EXCEPTRSNCODE       object
EXCEPTRSNDESC       object
SEVERITYCODE.1       int64
SEVERITYDESC        object
COLLISIONTYPE       object
PERSONCOUNT          int64
PEDCOUNT             int64
PEDCYLCOUNT          int64
VEHCOUNT             int64
INCDATE             object
INCDTTM             object
JUNCTIONTYPE        object
SDOT_COLCODE         int64
SDOT_COLDESC        object
INATTENTIONIND      object
UNDERINFL           object
WEATHER               int8
ROADCOND              int8
LIGHTCOND         category
PEDROWNOTGRNT       object
SDOTCOLNUM         float64
SPEEDING            object
ST_COLCODE          object
ST_COLDESC          object
SEGLANEKEY           int64
CROSSWALKKEY         int64
H

In [22]:
df["LIGHTCOND"]=df["LIGHTCOND"].cat.codes
df

SEVERITYCODE           X          Y  OBJECTID  INCKEY  COLDETKEY  \
0                  2 -122.323148  47.703140         1    1307       1307   
1                  1 -122.347294  47.647172         2   52200      52200   
2                  1 -122.334540  47.607871         3   26700      26700   
3                  1 -122.334803  47.604803         4    1144       1144   
4                  2 -122.306426  47.545739         5   17700      17700   
5                  1 -122.387598  47.690575         6  320840     322340   
6                  1 -122.338485  47.618534         7   83300      83300   
7                  2 -122.320780  47.614076         9  330897     332397   
8                  1 -122.335930  47.611904        10   63400      63400   
9                  2 -122.384700  47.528475        12   58600      58600   
10                 1         NaN        NaN        14   48900      48900   
11                 1 -122.333831  47.547371        15   38800      38800   
12                 1 -122.356273  47.571375        16    2771       2771   
13                 1 -122.323966  47.606374        17   32800      32800   
14                 2 -122.317414  47.664028        19    1212       1212   
15                 1 -122.337663  47.617510        20  330878     332378   
16                 2 -122.344539  47.692012        21   46300      46300   
17                 1         NaN        NaN        23   23000      23000   
18                 2 -122.328270  47.571420        24  330833     332333   
19                 1 -122.383802  47.583715        25   97100      97100   
20                 2 -122.292403  47.732847        26    1347       1347   
21                 2 -122.313786  47.708535        28    1323       1323   
22                 1 -122.318169  47.615837        29   80000      80000   
23                 1 -122.337486  47.589746        31   28700      28700   
24                 2 -122.279658  47.553405        33    1268       1268   
25                 2 -122.312857  47.599218        34  320932     322432   
26                 1 -122.330730  47.615450        35  113300     113300   
27                 1 -122.385859  47.581191        36   64700      64700   
28                 1 -122.304990  47.611474        37    1083       1083   
29                 1         NaN        NaN        38   61500      61500   
...              ...         ...        ...       ...     ...        ...   
194643             1 -122.345863  47.612991    219510  307577     308857   
194644             1 -122.330298  47.603233    219511  312117     313537   
194645             2 -122.328079  47.604161    219512  307692     308972   
194646             1 -122.320756  47.608656    219513  312289     313709   
194647             2 -122.355449  47.704720    219514  308575     309855   
194648             1 -122.357624  47.635956    219515  307792     309072   
194649             2 -122.302382  47.626759    219516  307985     309265   
194650             2 -122.355298  47.684382    219517  310417     311717   
194651             1 -122.320780  47.614076    219519  309594     310874   
194652             1 -122.335527  47.617434    219520  308698     309978   
194653             2 -122.322097  47.649615    219521  308342     309622   
194654             1 -122.312679  47.719414    219522  311117     312437   
194655             2 -122.380016  47.664879    219523  310911     312231   
194656             2 -122.340474  47.614496    219524  312179     313599   
194657             1 -122.337137  47.610709    219525  307834     309114   
194658             1 -122.302554  47.584099    219528  311697     313057   
194659             1 -122.298955  47.717456    219529  308019     309299   
194660             2         NaN        NaN    219531  308990     310270   
194661             2 -122.306092  47.617881    219532  308532     309812   
194662             1 -122.337880  47.625793    219535  307802     309082   
194663             2 -122.299160  47.579673    219536  3

In [23]:
#assigning numerical values and storing it in another colum called "WEATHER_cat"
df["LIGHTCOND_cat"]=labelencoder.fit_transform(df["LIGHTCOND"])
#Display DataFrame
df

SEVERITYCODE           X          Y  OBJECTID  INCKEY  COLDETKEY  \
0                  2 -122.323148  47.703140         1    1307       1307   
1                  1 -122.347294  47.647172         2   52200      52200   
2                  1 -122.334540  47.607871         3   26700      26700   
3                  1 -122.334803  47.604803         4    1144       1144   
4                  2 -122.306426  47.545739         5   17700      17700   
5                  1 -122.387598  47.690575         6  320840     322340   
6                  1 -122.338485  47.618534         7   83300      83300   
7                  2 -122.320780  47.614076         9  330897     332397   
8                  1 -122.335930  47.611904        10   63400      63400   
9                  2 -122.384700  47.528475        12   58600      58600   
10                 1         NaN        NaN        14   48900      48900   
11                 1 -122.333831  47.547371        15   38800      38800   
12                 1 -122.356273  47.571375        16    2771       2771   
13                 1 -122.323966  47.606374        17   32800      32800   
14                 2 -122.317414  47.664028        19    1212       1212   
15                 1 -122.337663  47.617510        20  330878     332378   
16                 2 -122.344539  47.692012        21   46300      46300   
17                 1         NaN        NaN        23   23000      23000   
18                 2 -122.328270  47.571420        24  330833     332333   
19                 1 -122.383802  47.583715        25   97100      97100   
20                 2 -122.292403  47.732847        26    1347       1347   
21                 2 -122.313786  47.708535        28    1323       1323   
22                 1 -122.318169  47.615837        29   80000      80000   
23                 1 -122.337486  47.589746        31   28700      28700   
24                 2 -122.279658  47.553405        33    1268       1268   
25                 2 -122.312857  47.599218        34  320932     322432   
26                 1 -122.330730  47.615450        35  113300     113300   
27                 1 -122.385859  47.581191        36   64700      64700   
28                 1 -122.304990  47.611474        37    1083       1083   
29                 1         NaN        NaN        38   61500      61500   
...              ...         ...        ...       ...     ...        ...   
194643             1 -122.345863  47.612991    219510  307577     308857   
194644             1 -122.330298  47.603233    219511  312117     313537   
194645             2 -122.328079  47.604161    219512  307692     308972   
194646             1 -122.320756  47.608656    219513  312289     313709   
194647             2 -122.355449  47.704720    219514  308575     309855   
194648             1 -122.357624  47.635956    219515  307792     309072   
194649             2 -122.302382  47.626759    219516  307985     309265   
194650             2 -122.355298  47.684382    219517  310417     311717   
194651             1 -122.320780  47.614076    219519  309594     310874   
194652             1 -122.335527  47.617434    219520  308698     309978   
194653             2 -122.322097  47.649615    219521  308342     309622   
194654             1 -122.312679  47.719414    219522  311117     312437   
194655             2 -122.380016  47.664879    219523  310911     312231   
194656             2 -122.340474  47.614496    219524  312179     313599   
194657             1 -122.337137  47.610709    219525  307834     309114   
194658             1 -122.302554  47.584099    219528  311697     313057   
194659             1 -122.298955  47.717456    219529  308019     309299   
194660             2         NaN        NaN    219531  308990     310270   
194661             2 -122.306092  47.617881    219532  308532     309812   
194662             1 -122.337880  47.625793    219535  307802     309082   
194663             2 -122.299160  47.579673    219536  3

In [24]:
import numpy as np
X = np.asarray(df[['WEATHER_cat', 'ROADCOND_cat', 'LIGHTCOND_cat']])
X[0:5]

array([[5, 9, 6],
       [7, 9, 3],
       [5, 1, 6],
       [2, 1, 6],
       [7, 9, 6]], dtype=int64)

<h1>Normalize the dataset<h1>

In [25]:
from sklearn import preprocessing

In [26]:
X=preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\utils\validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, _DataConversionWarning)


array([[ 0.35364615,  1.50545441,  0.3912104 ],
       [ 1.04520829,  1.50545441, -1.18714134],
       [ 0.35364615, -0.68713674,  0.3912104 ],
       [-0.68369706, -0.68713674,  0.3912104 ],
       [ 1.04520829,  1.50545441,  0.3912104 ]])

<h1> Train/Test Split <h1>

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
# split a dataset into train and test sets
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
# create dataset
X, y = make_blobs(n_samples=116376)
# split into train test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=1)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(81463, 2) (34913, 2) (81463,) (34913,)


In [29]:
#X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.3,random_state=1)
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=1)
print("Train set:",X_train.shape, y_train.shape)
print("Test set:",X_test.shape, y_test.shape)

Train set: (81463, 2) (81463,)
Test set: (34913, 2) (34913,)


<h1>KKN<h1>

After balancing SEVERITYCODE feature, and standardizing the input feature, the data has been ready for building machine learning models.
I have employed three machine learning models:
K Nearest Neighbour (KNN)
Decision Tree
Linear Regression
After importing necessary packages and splitting preprocessed data into test and train sets, for each machine learning model, I have built and evaluated the model and shown the results as follow:

In [30]:
from sklearn.neighbors import KNeighborsClassifier
k=25
knn=KNeighborsClassifier(n_neighbors=k).fit(X_train,y_train)
knn_y_pred=knn.predict(X_test)
knn_y_pred[0:5]

array([1, 2, 1, 1, 1])

<h1>KKN Evaluation<h1>

Method 1

In [31]:
import numpy as np
from sklearn.metrics import jaccard_similarity_score

In [59]:
#jaccard similarity score
jaccard_similarity_score(y_test,knn_y_pred)


0.99994271474808816

In [33]:
from sklearn.metrics import f1_score

In [56]:
#f1 SCORE
f1_score(y_test,knn_y_pred,average="macro")

0.99994253614826212

Method 2

In [35]:
from sklearn.metrics import classification_report,confusion_matrix

In [36]:
print(confusion_matrix(y_test,knn_y_pred))
print(classification_report(y_test,knn_y_pred))

[[11594     2     0]
 [    0 11607     0]
 [    0     0 11710]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00     11596
          1       1.00      1.00      1.00     11607
          2       1.00      1.00      1.00     11710

avg / total       1.00      1.00      1.00     34913



<h1> Decision tree<h1>

In [37]:
#Building the Decision Tree
from sklearn.tree import DecisionTreeClassifier
colDataTree= DecisionTreeClassifier(criterion="entropy",max_depth=7)
colDataTree
colDataTree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=7,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [38]:
#Train Model and Predict
DTyhat=colDataTree.predict(X_test)
print(DTyhat[0:5])
print(y_test[0:5])

[1 2 1 1 1]
[1 2 1 1 1]


Method 1

In [39]:
import numpy as np
from sklearn.metrics import jaccard_similarity_score

In [58]:
#jaccard similarity score
jaccard_similarity_score(y_test,DTyhat)

0.99991407212213212

In [41]:
from sklearn.metrics import f1_score

In [55]:
#f1 SCORE
f1_score(y_test,DTyhat,average="macro")

0.99991380421807052

Method 2

In [43]:
from sklearn.metrics import classification_report,confusion_matrix

In [44]:
print(confusion_matrix(y_test,DTyhat))
print(classification_report(y_test,DTyhat))

[[11593     3     0]
 [    0 11607     0]
 [    0     0 11710]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00     11596
          1       1.00      1.00      1.00     11607
          2       1.00      1.00      1.00     11710

avg / total       1.00      1.00      1.00     34913



<h1> Logistic Regression<h1>

In [45]:
#Building the LR Model
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR=LogisticRegression(C=6,solver="liblinear").fit(X_train,y_train)
LR

LogisticRegression(C=6, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [46]:
#Train Model and predicr
LRyhat=LR.predict(X_test)
LRyhat

array([1, 2, 1, ..., 0, 1, 2])

In [47]:
yhat_prob=LR.predict_proba(X_test)
yhat_prob

array([[  9.33007730e-04,   9.99065827e-01,   1.16506199e-06],
       [  1.89359175e-25,   9.14795585e-02,   9.08520442e-01],
       [  4.17263336e-03,   9.93327286e-01,   2.50008034e-03],
       ..., 
       [  9.84643780e-01,   1.53562167e-02,   3.47020919e-09],
       [  1.32069606e-05,   9.99983372e-01,   3.42098526e-06],
       [  3.42873223e-25,   1.27913484e-01,   8.72086516e-01]])

Method 1

In [48]:
import numpy as np
from sklearn.metrics import jaccard_similarity_score

In [57]:
#jaccard similarity score
jaccard_similarity_score(y_test,LRyhat)

0.99977085899235241

In [50]:
from sklearn.metrics import f1_score

In [51]:
#f1 SCORE
f1_score(y_test,LRyhat,average="macro")

0.99977014464428127

Method 2

In [52]:
from sklearn.metrics import classification_report,confusion_matrix

In [53]:
print(confusion_matrix(y_test,LRyhat))
print(classification_report(y_test,LRyhat))

[[11594     2     0]
 [    6 11601     0]
 [    0     0 11710]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00     11596
          1       1.00      1.00      1.00     11607
          2       1.00      1.00      1.00     11710

avg / total       1.00      1.00      1.00     34913



In [54]:
import pip
pip.main(["install","jaccard-index"])



Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.


You should consider upgrading via the 'C:\Users\ASUS\Anaconda3\python.exe -m pip install --upgrade pip' command.


0

<h1>Results and Evaluations<h1>

In [77]:
import pandas as pd
data = [['KNN',0.999943,0.99994271474808816],['Decision Tree',0.999914,0.99991407212213212],['Linear Regresion',0.999770,0.99977085899235241]]
df = pd.DataFrame(data,columns=['Mode','F1 Score','jaccard similarity score'])
print(df) 

               Mode  F1 Score  jaccard similarity score
0               KNN  0.999943                  0.999943
1     Decision Tree  0.999914                  0.999914
2  Linear Regresion  0.999770                  0.999771


Based on the above table, KNN is the best model to predict car accident severity.